"""create finance schema

Revision ID: 261ebc5ee393
Revises: 
Create Date: 2026-07-01 18:24:31.710541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261ebc5ee393'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_grade_policy',
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('grade_rank', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Integer(), nullable=False),
    sa.Column('base_interest_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('grade'),
    sa.UniqueConstraint('grade_rank')
    )
    credit_grade_policy_table = sa.table(
        'credit_grade_policy',
        sa.column('grade', sa.String(length=2)),
        sa.column('grade_rank', sa.Integer()),
        sa.column('min_score', sa.Integer()),
        sa.column('max_score', sa.Integer()),
        sa.column('credit_limit', sa.Integer()),
        sa.column('base_interest_rate', sa.Numeric(precision=4, scale=2)),
    )
    op.bulk_insert(
        credit_grade_policy_table,
        [
            {'grade': 'A+', 'grade_rank': 1, 'min_score': 95, 'max_score': 100, 'credit_limit': 5000000, 'base_interest_rate': 3.0},
            {'grade': 'A', 'grade_rank': 2, 'min_score': 90, 'max_score': 94, 'credit_limit': 4500000, 'base_interest_rate': 3.5},
            {'grade': 'A-', 'grade_rank': 3, 'min_score': 85, 'max_score': 89, 'credit_limit': 4000000, 'base_interest_rate': 4.0},
            {'grade': 'B+', 'grade_rank': 4, 'min_score': 75, 'max_score': 84, 'credit_limit': 3500000, 'base_interest_rate': 4.5},
            {'grade': 'B', 'grade_rank': 5, 'min_score': 65, 'max_score': 74, 'credit_limit': 3000000, 'base_interest_rate': 5.5},
            {'grade': 'B-', 'grade_rank': 6, 'min_score': 60, 'max_score': 64, 'credit_limit': 2500000, 'base_interest_rate': 6.0},
            {'grade': 'C+', 'grade_rank': 7, 'min_score': 55, 'max_score': 59, 'credit_limit': 2000000, 'base_interest_rate': 7.0},
            {'grade': 'C', 'grade_rank': 8, 'min_score': 50, 'max_score': 54, 'credit_limit': 1000000, 'base_interest_rate': 8.5},
            {'grade': 'C-', 'grade_rank': 9, 'min_score': 45, 'max_score': 49, 'credit_limit': 800000, 'base_interest_rate': 9.5},
            {'grade': 'D+', 'grade_rank': 10, 'min_score': 35, 'max_score': 44, 'credit_limit': 600000, 'base_interest_rate': 11.0},
            {'grade': 'D', 'grade_rank': 11, 'min_score': 25, 'max_score': 34, 'credit_limit': 400000, 'base_interest_rate': 13.0},
            {'grade': 'D-', 'grade_rank': 12, 'min_score': 15, 'max_score': 24, 'credit_limit': 300000, 'base_interest_rate': 15.0},
            {'grade': 'F+', 'grade_rank': 13, 'min_score': 8, 'max_score': 14, 'credit_limit': 200000, 'base_interest_rate': 18.0},
            {'grade': 'F', 'grade_rank': 14, 'min_score': 3, 'max_score': 7, 'credit_limit': 100000, 'base_interest_rate': 20.0},
            {'grade': 'F-', 'grade_rank': 15, 'min_score': 0, 'max_score': 2, 'credit_limit': 0, 'base_interest_rate': 0.0},
        ],
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('profile_image_seed', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.Enum('employee', 'freelancer', 'other'), nullable=False),
    sa.Column('monthly_salary', sa.Integer(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('provider', sa.Enum('local', 'kakao', 'google'), server_default='local', nullable=False),
    sa.Column('social_id', sa.String(length=255), nullable=True),
    sa.Column('onboarding_step', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('credit_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('loan_payment', 'overdue', 'loan_complete', 'loan_default'), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('expense_type', sa.Enum('fixed', 'variable'), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_expenses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('applied_credit_grade', sa.String(length=2), nullable=False),
    sa.Column('applied_credit_score', sa.Integer(), nullable=False),
    sa.Column('applied_limit', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('principal', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('monthly_payment', sa.Integer(), nullable=False),
    sa.Column('total_repayment', sa.Integer(), nullable=False),
    sa.Column('remaining_balance', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed'), server_default='active', nullable=False),
    sa.Column('started_turn', sa.Integer(), nullable=False),
    sa.Column('active_user_id', sa.BigInteger(), sa.Computed("CASE WHEN status = 'active' THEN user_id ELSE NULL END", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['applied_credit_grade'], ['credit_grade_policy.grade'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_user_id', name='uq_loans_one_active_per_user')
    )
    op.create_table('simulation_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current_turn', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('current_year', sa.Integer(), nullable=False),
    sa.Column('current_month', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('consume_score', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('stock_holdings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_type', sa.Enum('high_vol', 'low_vol', 'index'), nullable=False),
    sa.Column('principal', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_type', name='uq_stock_holdings_user_type')
    )
    op.create_table('turns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('salary_received', sa.Integer(), nullable=False),
    sa.Column('fixed_expense_total', sa.Integer(), nullable=False),
    sa.Column('variable_expense_total', sa.Integer(), nullable=False),
    sa.Column('food_choice', sa.Enum('save', 'normal', 'some', 'much'), nullable=False),
    sa.Column('shopping_choice', sa.Enum('save', 'normal', 'some', 'much'), nullable=False),
    sa.Column('leisure_choice', sa.Enum('save', 'normal', 'some', 'much'), nullable=False),
    sa.Column('consume_score_delta', sa.Integer(), nullable=False),
    sa.Column('credit_score_delta', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('loan_repayment_amount', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('cash_balance_after', sa.Integer(), nullable=False),
    sa.Column('total_asset_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'turn_number', name='uq_turns_user_turn')
    )
    op.create_table('repayment_schedule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_turn', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'overdue'), server_default='pending', nullable=False),
    sa.Column('paid_at_turn', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'installment_number', name='uq_repayment_loan_installment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment_schedule')
    op.drop_table('turns')
    op.drop_table('stock_holdings')
    op.drop_table('simulation_state')
    op.drop_table('loans')
    op.drop_table('fixed_expenses')
    op.drop_table('expenses')
    op.drop_table('credit_history')
    op.drop_table('users')
    op.drop_table('credit_grade_policy')
    # ### end Alembic commands ###
